import { inter } from "@app/fonts";
import type { Metadata } from "next";
import '../styles/globals.css';


export const metadata: Metadata = {
  title: "Scribble It!",
  description: "Generated by create next app",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-scrbb-main-white antialiased ${inter.className} text-scrbb-black`}>
        {children}
      </body>
    </html>
  );
}


export default RootLayout;
